name: Build, Test, Lint for Pull Requests

on:
  pull_request:
    branches:
      - main
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.19"

      - name: Install
        run: npm ci

      - name: Build
        run: npm run setup

      - name: Test
        run: npm run test --verbose

      - name: Lint
        run: npm run lint
  # Cypress:
  #   runs-on: ubuntu-latest
  #   needs: build-lint-test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: "12.19"
  #     # just so we learn about available environment variables GitHub provides
  #     - name: Print env variables
  #       run: |
  #         npm i -g @bahmutov/print-env
  #         print-env GITHUB

  #     - name: Cypress tests
  #       run: npm run test:ci
  #       env:
  #         # place your secret record key at
  #         # https://github.com/cypress-io/cypress-example-kitchensink/settings/secrets
  #         # CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}
  #         TERM: xterm
